# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
